events.observeNotification();
events.on("notification", function (n) {
    if (n.getPackageName() === "com.android.mms") {
        log("收到验证码通知")
        app.launch("com.android.mms")
        sleep(1000)
        id("avatar").findOne().parent().click()
        sleep(1000)
        id("action_btn").findOne().click()
        app.launch("com.tencent.mm")
        id("icon_tv").className("android.widget.TextView").text("通讯录").findOne().parent().parent().click()
        id("jha").findOne().click()
        sleep(1000)
        setText("文件传输助手")
        sleep(1000)
        id("mem").className("android.widget.LinearLayout").depth(11).findOne().parent().click()
        sleep(1000)
        longClick(200, 2500)
        sleep(1000)
        click(120, 2400)
        sleep(1000)
        id("bql").findOne().click()
        recents()
        sleep(500)
        swipe(500, 1000, 100, 1000, 300)
        home()
    }
    sleep(1000)
})
